steps:
  # Étape pour construire l'application Spring Boot
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']

  # Étape pour construire l'image Docker de l'application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/multiplication', '.']

  # Étape pour pousser l'image Docker vers Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/multiplication']

  # Étape pour déployer l'image Docker sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'multiplication', '--image=gcr.io/$PROJECT_ID/multiplication', '--region=us-central1']
