steps:
  # Compilation de l'application Spring Boot avec Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']

  # Copie du fichier JAR compilé vers Google Cloud Storage (GCS)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', './multiplication-0.0.1-SNAPSHOT.jar', 'gs://appspring/']

  # Téléchargement du fichier JAR depuis Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://appspring/multiplication-0.0.1-SNAPSHOT.jar', '/home/molkaghammam2']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'molkaghammam2@instance-20240227-124824'
      - '--zone=us-central1-a'
      - '--command'
      - 'java -jar /home/molkaghammam2/springapp/multiplication-0.0.1-SNAPSHOT.jar'    
