steps:
  # Compilation de l'application Spring Boot avec Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']

  # Copie du fichier JAR compilé vers Google Cloud Storage (GCS)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', './multiplication-0.0.1-SNAPSHOT.jar', 'gs://appspring/']

  # Téléchargement du fichier JAR depuis Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://appspring/multiplication-0.0.1-SNAPSHOT.jar', '/home/molkaghammam2']

  # Déploiement de l'application sur la machine virtuelle
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'instance-20240227-124824', '--command', 'java -jar /home/molkaghammam2/multiplication-0.0.1-SNAPSHOT.jar']
